import type { StudioAsset, StudioDraft } from "./studio-contract";
export const exampleAssets: StudioAsset[] = [
  {
    imageId: "hero",
    url: "/studio/asset-1.png",
    width: 1200,
    height: 1200,
    alt: "금속 다기 작품 예시",
    asset_mode: "source",
    product_generated: false,
    fidelity_status: "FALLBACK",
  },
  {
    imageId: "detail",
    url: "/studio/asset-3.png",
    width: 1200,
    height: 1200,
    alt: "금속 다기 디테일 예시",
    asset_mode: "source",
    product_generated: false,
    fidelity_status: "FALLBACK",
  },
];
export const sectionLabels: Record<string, string> = {
  hero: "작품 소개",
  statement: "작품 이야기",
  feature_grid: "작품의 특징",
  detail_split: "디테일",
  wide_image: "전체 이미지",
  gallery: "작품 갤러리",
  usage_scene: "사용 장면",
  scale_reference: "크기 안내",
  palette: "색상",
  recommendation: "추천",
  info_table: "작품 정보",
  notice: "관리 및 안내",
  closing: "마무리",
};
export const exampleDraft: StudioDraft = {
  product_name: "시간을 담은 금속 다기",
  product_type: "공예 다기",
  summary: "차를 마시는 순간에 더하는, 손으로 만든 아름다움.",
  hero_headline: "오래 머무는 아름다움,\n차 한 잔에 담다.",
  hero_description:
    "손끝에서 시작된 섬세한 곡선과 은은한 빛.\n일상의 차 한 잔을 조금 더 특별하게 만들어 보세요.",
  usage_scene: "차를 즐기는 시간",
  features: [],
  keywords: ["금속공예", "다기", "수공예"],
  layout_id: "editorial-split",
  page_plan: [
    {
      section_id: "hero",
      block_type: "hero",
      eyebrow: "CRAFTED FOR YOUR EVERYDAY",
      title: "오래 머무는 아름다움,\n차 한 잔에 담다.",
      body: "손끝에서 시작된 섬세한 곡선과 은은한 빛.\n일상의 차 한 잔을 조금 더 특별하게 만들어 보세요.",
      variant: "paper",
      photo_id: "hero",
      photo_ids: [],
      items: [],
    },
    {
      section_id: "story",
      block_type: "statement",
      eyebrow: "THE STORY",
      title: "손으로 빚어낸, 고유한 표정",
      body: "작품의 제작 과정과 담고 싶은 이야기를 들려주세요. 재료를 고르는 순간부터 마지막 손길까지, 작품의 가치를 전합니다.",
      variant: "soft",
      photo_id: "",
      photo_ids: [],
      items: [],
    },
    {
      section_id: "details",
      block_type: "detail_split",
      eyebrow: "A CLOSER LOOK",
      title: "가까이 볼수록 깊어지는 매력",
      body: "사진 속 형태와 표면을 자세히 확인해 보세요. 실제 작품의 소재와 제작 방식은 판매자가 확인한 정보로 작성해 주세요.",
      variant: "paper",
      photo_id: "detail",
      photo_ids: [],
      items: [],
    },
    {
      section_id: "features",
      block_type: "feature_grid",
      eyebrow: "THOUGHTFUL DETAILS",
      title: "일상에 자연스럽게 스며들도록",
      body: "작품에서 가장 소개하고 싶은 특징을 적어주세요.",
      variant: "soft",
      photo_id: "",
      photo_ids: [],
      items: [
        {
          title: "형태",
          description: "부드러운 곡선으로 이루어진 작품의 형태",
        },
        { title: "표면", description: "빛에 따라 달라 보이는 표면의 표정" },
      ],
    },
    {
      section_id: "care",
      block_type: "notice",
      eyebrow: "CARE GUIDE",
      title: "오래 함께하기 위한 안내",
      body: "소재에 맞는 세척 방법과 보관 시 주의사항을 확인해 주세요. 정확한 관리법은 제작자의 안내를 따라주세요.",
      variant: "paper",
      photo_id: "",
      photo_ids: [],
      items: [],
    },
    {
      section_id: "closing",
      block_type: "closing",
      eyebrow: "MIDAM · CRAFTED STORIES",
      title: "당신의 일상에, 한 점의 이야기",
      body: "오랜 시간 곁에 두고 싶은 작품을 만나보세요.",
      variant: "ink",
      photo_id: "",
      photo_ids: [],
      items: [],
    },
  ],
};
